/**
 * @description       : 
 * @author            : Amit Mathur
 * @group             : 
 * @last modified on  : 12-05-2021
 * @last modified by  : Amit Mathur
 * Modifications Log 
 * Ver   Date         Author        Modification
 * 1.0   12-05-2021   Amit Mathur   Initial Version
**/
public with sharing class TestsalesClass {
    public TestsalesClass() {
System.debug('Hello GitHub Users');
System.debug('New Debug Statement..');
    }
}
